name: SimpliciteAddons
author: roblikescake
main: net.simplicite_mc.roblikescake.simpliciteaddons.SimpliciteAddons
description: It does stuff.
version: ${project.version}.${BUILD_NUMBER}

commands:
   bed:
      description: Teleports you to your Bed location.

   spawn:
      description: Teleports you to the Server Spawn location.

   setspawn:
      description: Sets the Server Spawn Location.

   motd:
      description: Displays the PlayerMOTD.

   getsponge:
      desription: Gives you a sponge.
